### ISSUE TITLE
cookie_store 0.16 breaks reqwest_cookie_store::CookieStoreMutex::new

### ISSUE THREAD

**Issue by aknarts** [pfernie/reqwest_cookie_store#2]
Using pretty much the code from the readme fails now 
```
error[E0308]: mismatched types
  --> src/lib.rs:94:72
   |
94 |         let cookie_store = reqwest_cookie_store::CookieStoreMutex::new(store);
   |                                                                        ^^^^^ expected struct `cookie_store::cookie_store::CookieStore`, found struct `cookie_store::CookieStore`
   |
   = note: perhaps two different versions of crate `cookie_store` are being used?
```
Please update the Cargo.toml to use the proper version of the other crate

**Comment by pfernie** [comment]
Thanks for the PR; this is merged & [0.3.0](https://crates.io/crates/reqwest_cookie_store/0.3.0) is published.

**Comment by albel727** [comment]
I've run into this too. Please consider just `pub use` reexporting `cookie_store` from `reqwest_cookie_store`, so that the library user isn't forced to specify a possibly conflicting `cookie_store` version dependency in `Cargo.toml` and could just use the guaranteed compatible `CookieStore` type from your crate instead.

**Comment by pfernie** [comment]
Thank you for the suggestion; this is done in the [0.4.0 release](https://crates.io/crates/reqwest_cookie_store/0.4.0)

**Comment by albel727** [comment]
Nice! I've put it to use right away, thanks.
